### ISSUE TITLE
java.lang.NoClassDefFoundError: org/json/simple/JSONValue

### ISSUE THREAD

**Issue by zafarella** [GoDaddy-Hosting/ruby-sonar-plugin#8]
Guys, any remedy for this one?

```
ERROR: Error during Sonar runner execution
org.sonar.runner.impl.RunnerException: Unable to execute Sonar
        at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
        at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
        at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
        at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
        at org.sonar.runner.api.Runner.execute(Runner.java:100)
        at org.sonar.runner.Main.executeTask(Main.java:70)
        at org.sonar.runner.Main.execute(Main.java:59)
        at org.sonar.runner.Main.main(Main.java:53)
Caused by: java.lang.NoClassDefFoundError: org/json/simple/JSONValue
        at com.godaddy.sonar.ruby.simplecovrcov.SimpleCovRcovJsonParserImpl.parse(SimpleCovRcovJsonParserImpl.java:30)
        at com.godaddy.sonar.ruby.simplecovrcov.SimpleCovRcovSensor.calculateMetrics(SimpleCovRcovSensor.java:114)
        at com.godaddy.sonar.ruby.simplecovrcov.SimpleCovRcovSensor.analyse(SimpleCovRcovSensor.java:81)
        at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
        at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
        at org.sonar.batch.phases.PhaseExecutor.execute(PhaseExecutor.java:98)
        at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:100)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:85)
        at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:258)
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:253)
        at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:243)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:100)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:85)
        at org.sonar.batch.bootstrap.GlobalContainer.executeAnalysis(GlobalContainer.java:153)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:110)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:76)
        at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
        ... 9 more
Caused by: java.lang.ClassNotFoundException: org.json.simple.JSONValue
        at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
        ... 32 more
```

when doing

```
sonur-runner -X
```

`sonar-project.properties`

```

sonar.scm.provider=git
sonar.language=ruby
sonar.sourceEncoding=UTF-8
sonar.projectVersion=1.0
sonar.sources=app,lib
```

**Comment by mxsmith-godaddy** [comment]
How are you building the java project? Try to do a
maven clean (mvn clean)
and then perform  
maven install (mvn install)

**Comment by zafarella** [comment]
I did it like this actually, will take a look later on, why it's missing the lib

**Comment by panpanini** [comment]
I'm getting the same error when running mvn clean & mvn install

**Comment by eresse** [comment]
@zafarella @panpanini I was having the same issue so I forked the project : https://github.com/eresse/ruby-sonar-plugin

My version of the plugin works fine and reports coverage as well as complexity.

Cheers.
